USE realestate_db;
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (0, 'Roland','Dee De Leon','seller0@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (1, 'Patrick','Lam -Top #1 Producer','seller1@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (2, 'Heidi','Mueller','seller2@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (3, 'Serina','Molina','seller3@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (4, 'Pat','Holkesvig','seller4@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (5, 'Kristina','Tolento','seller5@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (6, 'Adrian','and Diane','seller6@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (7, 'Zoram','Luna','seller7@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (8, 'Julio','Sandoval','seller8@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (9, 'Shobha','George','seller9@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (10, 'Cerise','Jennings-Skeen','seller10@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (11, 'Michele','Campbell','seller11@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (12, 'Maria','Knorr','seller12@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (13, 'Colin','Miller','seller13@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (14, 'Joe','Corwin','seller14@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (15, 'Anthony','Koutsos','seller15@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (16, 'Home','Seekers Tampa Bay','seller16@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (17, 'Mark','Updegraff','seller17@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (18, 'Gina','Ibarra','seller18@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (19, 'Donna','Cornell','seller19@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (20, 'Terry','Gobbo','seller20@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (21, 'Anderson','Real Estate Group','seller21@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (22, 'Justin','& Geneen Sherrets','seller22@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (23, 'Jake','Worley','seller23@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (24, 'Darren','Soares','seller24@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (25, 'Anna','Chi Huang','seller25@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (26, 'Pro','Realty Group','seller26@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (27, 'Julie','Cothran','seller27@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (28, 'Joel','Nelson','seller28@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (29, 'Maggie','Caceres','seller29@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (30, 'Troy','Walseth','seller30@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (31, 'Steven','Michalski','seller31@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (32, 'Doron','Weisbarth','seller32@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (33, 'Brad','Griffin','seller33@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (34, 'Keith','Bruce','seller34@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (35, 'John','Manning','seller35@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (36, 'Natasha','Ochs & Deawn Seals','seller36@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (37, 'Justin','Green','seller37@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (38, 'The','Silverman Team','seller38@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (39, 'Mathew','Koshy','seller39@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (40, 'Maria','Woods','seller40@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (41, 'Military','Relocation Team','seller41@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (42, 'Kathy','Mason','seller42@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (43, 'Michael','Shiner, MBA','seller43@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (44, 'Joseph','Wieczorek','seller44@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (45, 'Shar','Rundio','seller45@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (46, 'Matthew','Long','seller46@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (47, 'Michael','Maio','seller47@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (48, 'Rich','Madden','seller48@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (49, 'Michael','Smith','seller49@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (50, 'NeChelle','Kennedy','seller50@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (51, 'Gilli','Axel','seller51@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (52, 'Matt','Clausen','seller52@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (53, 'Brian','Black','seller53@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (54, 'Duane','Burrows','seller54@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (55, 'Mike','McClanahan','seller55@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (56, 'Emily','Ryslinge','seller56@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (57, 'Paul','Lopez','seller57@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (58, 'Kevin','Roberts','seller58@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (59, 'Deanna','Chavis','seller59@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (60, 'Frederico','Viegas','seller60@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (61, 'Andrew','Pitarre','seller61@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (62, 'Jeff','Purcell','seller62@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (63, 'Mackey','Group Realty','seller63@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (64, 'Rocky',' Wilkinson','seller64@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (65, 'joseph','sabi','seller65@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (66, 'Yelena','Kokirtsev','seller66@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (67, 'Mark','Geller','seller67@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (68, 'Sarbjeet','Kaur  (SFR/SRS/CBR)','seller68@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (69, 'Valerie','Thomas','seller69@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (70, 'Andrew','Severino','seller70@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (71, 'Pavel','Balon','seller71@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (72, 'Phillip','LaPointe','seller72@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (73, 'Kerie','Edmead','seller73@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (74, 'Brian',' Kim','seller74@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (75, 'Diego','Rodriguez','seller75@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (76, 'Sarah','Ireland & Heather Burke','seller76@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (77, 'Rita','Nicolae','seller77@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (78, 'Heather','Schleeper','seller78@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (79, 'Tim','Combes','seller79@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (80, 'Sam','Lind','seller80@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (81, 'Michael','Forbis','seller81@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (82, 'Kenny','Fast','seller82@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (83, 'Al','Morrobel','seller83@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (84, 'Elbe','Real Estate','seller84@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (85, 'Kristy','Harper','seller85@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (86, 'Mary','Brooke Bonadies','seller86@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (87, 'Larry','& Laurie Webb','seller87@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (88, 'Jason','Miller','seller88@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (89, 'Bryan','Pellican','seller89@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (90, 'Velma','Medina','seller90@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (91, 'Robert','Elliott','seller91@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (92, 'Leo','Mendoza','seller92@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (93, 'risa','ziegler','seller93@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (94, 'Katy','Anastasio','seller94@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (95, 'Brice','Semrad','seller95@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (96, 'Kawing','Chiu','seller96@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (97, 'Dan','Schaffler','seller97@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (98, 'Gina',' Wilkinson','seller98@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (99, 'Sherry','Stetson','seller99@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (100, 'Jose','L Rodriguez','seller100@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (101, 'Windy','Humphreys','seller101@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (102, 'David',' Matney','seller102@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (103, 'Mike','Yowell / Monte Wilson','seller103@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (104, 'Devon','Stevens','seller104@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (105, 'Katie','Baccus','seller105@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (106, 'Anne',' Brownlee','seller106@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (107, 'Ben','Proctor','seller107@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (108, 'David','Nguyen','seller108@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (109, 'Mike','Zapart','seller109@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (110, 'JoEllen','Ufner - ABR,GRI,SFR','seller110@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (111, 'Ian','Sells - Top Area List Agent','seller111@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (112, 'Ryan','& Lilia Branco','seller112@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (113, 'Matt','Battiata','seller113@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (114, 'Miguel','Maldonado','seller114@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (115, 'Bradley','Rutledge','seller115@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (116, 'Anthony','Bishop','seller116@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (117, 'Juliana','Lee','seller117@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (118, 'Astha','Mathur','seller118@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (119, 'Jessa','Kellington','seller119@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (120, 'Racquel','Ludaway','seller120@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (121, 'Team','Ratcliffe','seller121@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (122, 'Brittain','Niemchak','seller122@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (123, 'Yana','Landman','seller123@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (124, 'Ricardo','Morales','seller124@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (125, 'Kyle','Gunter','seller125@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (126, 'Jason','Opland','seller126@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (127, 'Dino','Hasapis','seller127@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (128, 'Bob','Shiga Chgo Mag 5* Award','seller128@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (129, 'Clark','Anctil','seller129@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (130, 'Kim','Mathis','seller130@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (131, 'Amy','Pomerantz','seller131@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (132, 'Rachel','Crawford','seller132@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (133, 'Jeff','Grant','seller133@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (134, 'Carlos','Pastrana','seller134@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (135, 'Team','Rogers - Fathom Realty','seller135@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (136, 'Becky','Garcia Group','seller136@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (137, 'Jason','Farris','seller137@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (138, 'Kirby','Smith & Kallie Ritchey','seller138@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (139, 'Lauren','Stadjuhar','seller139@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (140, 'Michael','Wallen','seller140@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (141, 'AJ','Powers','seller141@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (142, 'Nate','Brill','seller142@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (143, 'Daisy','Edwards','seller143@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (144, 'Trey','Willard','seller144@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (145, 'Niko','Stathopoulos & Anthony Pappas','seller145@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (146, 'Eric','Mora','seller146@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (147, 'Carlos','Padilla','seller147@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (148, 'Kym','Plivelich','seller148@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (149, 'Todd','Stein','seller149@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (150, 'Shawn','Barton','seller150@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (151, 'John',' Chaffee','seller151@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (152, 'Siu','Fu Lau','seller152@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (153, 'The','Griffin Team','seller153@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (154, 'Darren','James','seller154@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (155, 'Christophe','Choo','seller155@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (156, 'Mitchell','Rosenwald','seller156@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (157, 'Pete','Dijkstra','seller157@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (158, 'Janet','Anderson','seller158@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (159, 'Prashant','Patel','seller159@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (160, 'Portia','Raff','seller160@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (161, 'Stephanie','Junca','seller161@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (162, 'Tracy','and Tego Venturi','seller162@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (163, 'Aaron','Carlson','seller163@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (164, 'Jason','Pennington','seller164@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (165, 'Jeff','Miller','seller165@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (166, 'Fred','Smith','seller166@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (167, 'Matthew','Neal','seller167@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (168, 'The','Debi Mestre Team','seller168@gmail.com','pass');
INSERT INTO SELLER (sid,fname,lname,email,password) VALUES (169, 'Gusty','Gulas','seller169@gmail.com','pass');
