#/bin/bash

python scraper.py akron-oh
python scraper.py albuquerque-nm
python scraper.py anaheim-ca
python scraper.py anchorage-ak
python scraper.py arlington-tx
python scraper.py arlington-va
python scraper.py atlanta-ga
python scraper.py aurora-co
python scraper.py austin-tx
python scraper.py bakersfield-ca
python scraper.py baltimore-md
python scraper.py baton-rouge-la
python scraper.py beverly-hills-ca
python scraper.py birmingham-al
python scraper.py boise-id
python scraper.py boston-ma
python scraper.py buffalo-ny
python scraper.py chandler-az
python scraper.py charlotte-nc
python scraper.py chesapeake-va
python scraper.py chicago-il
python scraper.py chula-vista-ca
python scraper.py cincinnati-oh
python scraper.py cleveland-oh
python scraper.py colorado-springs-co
python scraper.py columbus-oh
python scraper.py corpus-christi-tx
python scraper.py cupertino-ca
python scraper.py dallas-tx
python scraper.py denver-co
python scraper.py detroit-mi
python scraper.py durham-nc
python scraper.py el-paso-tx
python scraper.py fort-wayne-in
python scraper.py fort-worth-tx
python scraper.py fresno-ca
python scraper.py frisco-tx
python scraper.py garland-tx
python scraper.py glendale-az
python scraper.py greensboro-nc
python scraper.py henderson-nv
python scraper.py hialeah-fl
python scraper.py hollywood-ca
python scraper.py honolulu-hi
python scraper.py houston-tx
python scraper.py huntington-ny
python scraper.py indianapolis-in
python scraper.py jacksonville-fl
python scraper.py jersey-city-nj
python scraper.py kansas-city-mo
python scraper.py laredo-tx
python scraper.py las-vegas-nv
python scraper.py lincoln-ne
python scraper.py little-elm-tx
python scraper.py long-beach-ca
python scraper.py los-angeles-ca
python scraper.py lubbock-tx
python scraper.py madison-wi
python scraper.py memphis-tn
python scraper.py mesa-az
python scraper.py mesquite-tx
python scraper.py miami-fl
python scraper.py milwaukee-wi
python scraper.py minneapolis-mn
python scraper.py modesto-ca
python scraper.py montogomery-al
python scraper.py nashville-tn
python scraper.py new-orleans-la
python scraper.py new-york-ny
python scraper.py newark-nj
python scraper.py norfolk-va
python scraper.py north-hempstead-ny
python scraper.py oakland-ca
python scraper.py oklahoma-city-ok
python scraper.py omaha-ne
python scraper.py orlando-fl
python scraper.py philadelphia-pa
python scraper.py phoenix-az
python scraper.py pittsburgh-pa
python scraper.py plano-tx
python scraper.py portland-or
python scraper.py raleigh-nc
python scraper.py reno-nv
python scraper.py richardson-tx
python scraper.py riverside-ca
python scraper.py rochester-ny
python scraper.py sacramento-ca
python scraper.py san-antonio-tx
python scraper.py san-bernardino-ca
python scraper.py san-diego-ca
python scraper.py san-francisco-ca
python scraper.py san-jose-ca
python scraper.py santa-ana-ca
python scraper.py scottsdale-az
python scraper.py seattle-wa
python scraper.py st-louis-mo
python scraper.py st-paul-mn
python scraper.py st-petersburg-fl
python scraper.py stockton-ca
python scraper.py sunnyvale-tx
python scraper.py tampa-fl
python scraper.py toledo-oh
python scraper.py tucson-az
python scraper.py tulsa-ok
python scraper.py virginia-beach-va
python scraper.py washington-dc
python scraper.py wichita-ks
